name = "my-typescript-worker"
type = "webpack"
kv_namespaces = [
 { binding = "zdy", preview_id = "72dd7f2934964846b404cc8c3492293b", id = "72dd7f2934964846b404cc8c3492293b" }
]
zone_id = ""
account_id = "12bc8491cf29c1894cd16042e712bb63"
route = ""
workers_dev = true
compatibility_date = "2022-04-03"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
